### ISSUE TITLE
Cannot call another prompt inside submit prompt

### ISSUE THREAD

**Issue by jeffryhartanto** [impromptu/impromptu#90]
I use coffeescript and below is my submit prompt:

```
$.prompt "Opening Recap with ID "+Recap[0][0].id+".<br> Note: Any changes on Recap "+header.find("#recap_id").val()+" will not be saved.",
    title: "WARNING"
    buttons:
        "Continue": true
        "Cancel": false
    submit: (e, v, m, f) ->
        if v is true
            Recap_status = Recap[0][0].status
            LoadNewRecord(Recap, header)
            $("#error_history").hide()
        else
            selectedRecap()
```

Inside  `LoadNewRecord` I call another prompt which is below:

```
if period_lock >= getDateInput(Recap[0][0].recap_date) and Recap_status < 20
    setTimeout (->
        $.prompt "You are not allowed to make any changes for all documents before " +period_lock+ ".     Please contact your administrator for further information"
    return
    ), 100
```

Is there any idea how to fix this ?

Note:
if I remove the `$.prompt` inside `LoadNewRecode` or change it to `alert` everything works fine.

**Comment by koop** [comment]
Sorry, I think you're in the wrong place. I believe you're looking for the [jQuery Impromptu](http://trentrichardson.com/Impromptu/) plugin. This Impromptu is a command-line prompt (and is completely unrelated to the jQuery plugin). Good luck!
